### ISSUE TITLE
tryparse should not return Nullable

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/BioSymbols.jl#19]
The current method of `tryparse(AminoAcid, str)` returns a nullable value, which is the standard way of Julia 0.5 and 0.6. However, the next version of Julia (i.e. 0.7) will deprecate the nullable type and Julia 1.0 will remove it at all. Along with it, `tryparse` will be changed to return a "nothing"-able value of `Union{T,Nothing}` type. For example, `trypare(Int, "xxx")` returns `nothing` to indicate that it failed to parse the given string as an integer. We should respect the convention in the next version of BioSymbols.jl (maybe in BioSymbols.jl 0.3).

**Comment by Ward9250** [comment]
Indeed I wondered if we should do something about this now or later. I could have added it now with a static if that checks the version number. I can try this now and add it to version 2.0 if you like.

**Comment by bicycle1885** [comment]
Well, it sounds fine but it is a little bit too early to do that. Julia 0.7 is still in pre-alpha stage and it may change before its release. So, I think it is better only to remove deprecations in 2.0 and the actual API change should be delayed until the official release of Julia 1.0.

**Comment by Ward9250** [comment]
Ok cool, I'll add this to a version 0.3 milestone in the meantime.

**Comment by bicycle1885** [comment]
Version 3.0?

**Comment by Ward9250** [comment]
I assume BioSymbols with this syntax change would be a v3.0 as it could well break and be incompatible with past code?

**Comment by bicycle1885** [comment]
Yeah, but the milestone name is "Version 0.3", not "Version 3.0".

**Comment by Ward9250** [comment]
😆 apologies: a typo!

**Comment by BenJWard** [comment]
This has been fixed on branch version-3.0 now.
