### ISSUE TITLE
Remove iteration of BioSymbol

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSymbols.jl#41]
In Base Julia, almost anything can be iterated, e.g. integers. I really, really dislike that. How many times have you done something like
```
for i in n_iter
    foo()
end
```
only to find out you should have done `for i in 1:n_iter`? This weak typing causes unneeded errors, and I can't really think of a reason it should be there. In general, if you try to iterate a non-collection, something has gone wrong in your algorithm.

I suggest we remove `iterate` it from BioSymbols.

**Comment by kescobo** [comment]
In general, I agree. Would you still be able to have things like broadcasting be as generic as they could be?

```
julia> 1 .+ 1
2
```

To be honest I don't know if such things depend on being iterable or not

**Comment by jakobnissen** [comment]
I'm not sure. We need broadcasting for biosymbols, definitely. We'll have to figure that out before I change anything that shouldn't be changed.

**Comment by jakobnissen** [comment]
Added broadcasting.

**Comment by jakobnissen** [comment]
Closed in #43
