### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSymbols.jl#45]
Right, so we've made two breaking changes over the last months:

- [x] Remove conversion to/from integers (#38)
- [x] Remove iteration of biosymbols (#41)

I'd like to merge v5 soon, since it's required for BioSequences v3. Is anything missing that this package needs?

It would be neat to have an interface (#42), such that it was unabiguously clear what you needed to implement if you wanted to make a new BioSymbol type - but I don't think it's critical to get that into place, and changing the interface could risk being quite breaking, so I think we don't need to do it now, or perhaps ever.

**Comment by BenJWard** [comment]
@jakobnissen Ok, I'm going to cut a v5 release now. Holler if that's not good with you?

**Comment by jakobnissen** [comment]
Fine for me!

**Comment by jakobnissen** [comment]
Closing this issue as resolved, since v5 is out.
